### ISSUE TITLE
Example file fails to run

### ISSUE THREAD

**Issue by rbouckaert** [rbouckaert/snapper#4]
And it looks like this is not being picked up before release. Perhaps integration testing should be added to this repo (will be interesting to work out dependencies).

**Comment by davidjamesbryant** [comment]
I don’t understand what that means, but sounds good.



From: Remco Bouckaert ***@***.***>
Date: Monday, 6 September 2021 at 12:05 PM
To: rbouckaert/snapper ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rbouckaert/snapper] Example file fails to run (#4)

And it looks like this is not being picked up before release. Perhaps integration testing should be added to this repo (will be interesting to work out dependencies).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frbouckaert%2Fsnapper%2Fissues%2F4&data=04%7C01%7Cdavid.bryant%40otago.ac.nz%7C31d7de37717949e208c908d970ca0fa8%7C0225efc578fe4928b1579ef24809e9ba%7C1%7C0%7C637664835421863637%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Iu1eYZPEuf6SXsb4FClUBWj4GYxBSEAGM789f70OT8I%3D&reserved=0>, or unsubscribe<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAATIGSHHRQQICGLKLMERD3DUAQAVDANCNFSM5DPKQNMA&data=04%7C01%7Cdavid.bryant%40otago.ac.nz%7C31d7de37717949e208c908d970ca0fa8%7C0225efc578fe4928b1579ef24809e9ba%7C1%7C0%7C637664835421873591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=u04t%2BbsrANZVz%2FSsGRWEorDf13tXIcsDjwu52FQXYPo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdavid.bryant%40otago.ac.nz%7C31d7de37717949e208c908d970ca0fa8%7C0225efc578fe4928b1579ef24809e9ba%7C1%7C0%7C637664835421873591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NSCN4ypeHEYVbj%2B3Xi6KvZCAsTaHhgKxas3bcr9m4xE%3D&reserved=0> or Android<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdavid.bryant%40otago.ac.nz%7C31d7de37717949e208c908d970ca0fa8%7C0225efc578fe4928b1579ef24809e9ba%7C1%7C0%7C637664835421883540%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=07gjnPEjQwfGYTRPSI%2BfwhzC3RT9PpO9C%2BgYSIgxYDk%3D&reserved=0>.
